  find_package(GTest REQUIRED)
  include_directories(${GTEST_INCLUDE_DIRS})

  add_executable(test_MovAvg googletest/src/MovAvg/test_MovAvg_main.cpp)
  add_executable(test_MovMax googletest/src/MovMax/test_MovMax_main.cpp)
  add_executable(test_MovDev googletest/src/MovDev/test_MovDev_main.cpp)
  add_executable(test_MovGradient googletest/src/MovGradient/test_MovGradient_main.cpp)
  add_executable(test_MovPercentile googletest/src/MovPercentile/test_MovPercentile_main.cpp)
  add_executable(test_SchmittTrigger googletest/src/SchmittTrigger/test_SchmittTrigger_main.cpp)

  target_link_libraries(signal-estimator ${GTEST_LIBRARIES})
  target_link_libraries(test_MovAvg ${GTEST_LIBRARIES})
  target_link_libraries(test_MovMax ${GTEST_LIBRARIES})
  target_link_libraries(test_MovDev ${GTEST_LIBRARIES})
  target_link_libraries(test_MovGradient ${GTEST_LIBRARIES})
  target_link_libraries(test_MovPercentile ${GTEST_LIBRARIES})
  target_link_libraries(test_SchmittTrigger ${GTEST_LIBRARIES})

  add_test(NAME MovAvg COMMAND test_MovAvg)
  add_test(NAME MovMax COMMAND test_MovMax)
  add_test(NAME MovDev COMMAND test_MovDev)
  add_test(NAME MovGradient COMMAND test_MovGradient)
  add_test(NAME MovPercentile COMMAND test_MovPercentile)
  add_test(NAME SchmittTrigger COMMAND test_SchmittTrigger)